tracker:
  output:
    topic: "tracked_bounding_boxes"

tracker_visualizer:
  input:
    topic: "tracked_bounding_boxes"
  output:
    topic: "tracker_image"

subscribed_topics:
  camera_info:
    fx: 487.7295837402344
    fy: 487.5943908691406
    cx: 514.3927001953125
    cy: 384.86810302734375
  rgb_image:
    topic: "/robot/k4a_top/rgb/qhd/image"
    width: 1024
    height: 768
    frame_id: ""
  detection_bounding_box:
    topic: "/robot/k4a_top/rgbd_yolo_9dof_ros/bboxes3d"
    frame_id: ""
  tf_between_topics:
    q: [0.484, 0.506, -0.494, 0.515]
    t: [-0.028, -0.003, -0.047]