video_writer_subscribers:
  camera_reading:
    topic: "camera/rgb/image_raw"
    fps: 30
    width: 1280
    height: 720

  detections:
    topic: "norfair/output"

output_path: "/root/catkin_ws/src/publisher/src/example_out.mp4"
